#!/usr/bin/env bats
# Tests for ~/.dotfiles/claude/hooks/guard-commit.sh.
#
# Each test feeds a synthetic Bash payload (a git commit command) to the hook
# on stdin and asserts the exit code: 0 = allow, 2 = block.
#
# Run with: bats tests/

setup() {
  HOOK="$BATS_TEST_DIRNAME/../claude/hooks/guard-commit.sh"
}

run_guard_commit() {
  printf '%s' "$1" | jq -R '{tool_input: {command: .}}' | "$HOOK"
}

# passthrough: hook only inspects git commit commands

@test "passthrough: ls" {
  run run_guard_commit 'ls -la'
  [ "$status" -eq 0 ]
}

@test "passthrough: git status" {
  run run_guard_commit 'git status'
  [ "$status" -eq 0 ]
}

@test "passthrough: git push" {
  run run_guard_commit 'git push origin main'
  [ "$status" -eq 0 ]
}

# allow: normal commits

@test "allow: feat conventional commit" {
  run run_guard_commit 'git commit -m "feat: add foo"'
  [ "$status" -eq 0 ]
}

@test "allow: fix conventional commit" {
  run run_guard_commit 'git commit -m "fix: bar bug"'
  [ "$status" -eq 0 ]
}

@test "allow: chore with scope" {
  run run_guard_commit 'git commit -m "chore(claude): clean up settings"'
  [ "$status" -eq 0 ]
}

@test "allow: plain subject without prefix" {
  run run_guard_commit 'git commit -m "Update README with install steps"'
  [ "$status" -eq 0 ]
}

@test "allow: commit with single-quoted message" {
  run run_guard_commit "git commit -m 'feat: add foo'"
  [ "$status" -eq 0 ]
}

# block: AI signatures in body

@test "block: Co-Authored-By Claude" {
  run run_guard_commit 'git commit -m "feat: x" -m "Co-Authored-By: Claude <claude@anthropic.com>"'
  [ "$status" -eq 2 ]
}

@test "block: Generated by Claude" {
  run run_guard_commit 'git commit -m "Generated by Claude"'
  [ "$status" -eq 2 ]
}

@test "block: Generated with Claude" {
  run run_guard_commit 'git commit -m "Generated with Claude"'
  [ "$status" -eq 2 ]
}

# block: AI-tell phrasing in subject

@test "block: certainly in subject after conventional prefix" {
  run run_guard_commit 'git commit -m "feat: certainly add foo"'
  [ "$status" -eq 2 ]
}

@test "block: here is in subject" {
  run run_guard_commit 'git commit -m "fix: here is the patch"'
  [ "$status" -eq 2 ]
}

@test "block: i have at start of subject" {
  run run_guard_commit 'git commit -m "I have refactored the loop"'
  [ "$status" -eq 2 ]
}

@test "block: let me at start of subject" {
  run run_guard_commit 'git commit -m "let me clean this up"'
  [ "$status" -eq 2 ]
}

@test "block: in this commit phrasing" {
  run run_guard_commit 'git commit -m "in this commit we add the API"'
  [ "$status" -eq 2 ]
}
