package e2e

import (
	"fmt"
	"path/filepath"
	"strings"
	"testing"
)

// guardCommitPayload is a Bash payload carrying command, with cwd when set.
func guardCommitPayload(command, cwd string) map[string]any {
	p := map[string]any{"tool_input": map[string]any{"command": command}}
	if cwd != "" {
		p["cwd"] = cwd
	}
	return p
}

// guardCommitStubbed is a sandbox whose PATH resolves gitleaks to a stub
// that ignores its arguments and exits with code, decoupling the exit-code
// branches from real repo state.
func guardCommitStubbed(t *testing.T, code int) *Kit {
	k := New(t)
	stubs := t.TempDir()
	Stub(t, filepath.Join(stubs, "gitleaks"), fmt.Sprintf("exit %d\n", code))
	k.PrependPath(stubs)
	return k
}

func TestGuardCommit(t *testing.T) {
	// Each test feeds a synthetic Bash payload (a git commit command) to the
	// hook and asserts the exit code: 0 = allow, 2 = block.
	for _, tc := range []struct {
		name, command string
		status        int
	}{
		// passthrough: hook only inspects git commit commands
		{"passthrough: ls", "ls -la", 0},
		{"passthrough: git status", "git status", 0},
		{"passthrough: git push", "git push origin main", 0},
		// allow: normal commits
		{"allow: feat conventional commit", `git commit -m "feat: add foo"`, 0},
		{"allow: fix conventional commit", `git commit -m "fix: bar bug"`, 0},
		{"allow: chore with scope", `git commit -m "chore(claude): clean up settings"`, 0},
		{"allow: plain subject without prefix", `git commit -m "Update README with install steps"`, 0},
		{"allow: commit with single-quoted message", `git commit -m 'feat: add foo'`, 0},
		// block: AI signatures in body
		{"block: Co-Authored-By Claude", `git commit -m "feat: x" -m "Co-Authored-By: Claude <claude@anthropic.com>"`, 2},
		{"block: Generated by Claude", `git commit -m "Generated by Claude"`, 2},
		{"block: Generated with Claude", `git commit -m "Generated with Claude"`, 2},
		// block: AI-tell phrasing in subject
		{"block: certainly in subject after conventional prefix", `git commit -m "feat: certainly add foo"`, 2},
		{"block: here is in subject", `git commit -m "fix: here is the patch"`, 2},
		{"block: i have at start of subject", `git commit -m "I have refactored the loop"`, 2},
		{"block: let me at start of subject", `git commit -m "let me clean this up"`, 2},
		{"block: in this commit phrasing", `git commit -m "in this commit we add the API"`, 2},
	} {
		t.Run(tc.name, func(t *testing.T) {
			New(t).Hook("guard-commit", guardCommitPayload(tc.command, "")).Want(t, tc.status)
		})
	}

	// gitleaks staged-secret scan: exit-code branching (0 = clean, 1 = leak,
	// anything else = operational error, fails open).
	// Placement regression: the scan must run before the subject-parsing
	// early exit, so it fires even for commits whose -m message doesn't match
	// the quoted-message extraction regex (e.g. no surrounding quotes at all).
	// Entry guard regression: "git -C <dir> commit" must still be recognized
	// as a commit invocation. A prior version required "git" and "commit" to
	// be whitespace-adjacent, so the -C global flag broke the match and the
	// hook exited before the gitleaks scan ever ran.
	for _, tc := range []struct {
		name, command string
		code, status  int
		has           string
	}{
		{"allow: gitleaks exits 0 (clean scan)", `git commit -m "feat: add foo"`, 0, 0, ""},
		{"block: gitleaks exits 1 (leak found)", `git commit -m "feat: add foo"`, 1, 2, "gitleaks flagged a secret"},
		{"allow (fail open): gitleaks exits a non-0/1 operational error code", `git commit -m "feat: add foo"`, 2, 0, "gitleaks exited 2"},
		{"block: gitleaks leak is still caught with an unquoted -m message", "git commit -m foo", 1, 2, "gitleaks flagged a secret"},
		{"allow: unquoted -m message with a clean gitleaks scan still passes through", "git commit -m foo", 0, 0, ""},
		{"block: gitleaks leak is still caught with no -m at all (--allow-empty)", "git commit --allow-empty", 1, 2, ""},
		{"block: git -C <dir> commit is still caught by the entry guard (gitleaks leak)", "git -C " + t.TempDir() + " commit -m test", 1, 2, "gitleaks flagged a secret"},
		{"allow: plain git commit (no -C) is unaffected by the -C entry guard fix", "git commit -m test", 0, 0, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := guardCommitStubbed(t, tc.code).Hook("guard-commit", guardCommitPayload(tc.command, ""))
			r.Want(t, tc.status)
			if tc.has != "" {
				r.Has(t, tc.has)
			}
		})
	}

	t.Run("allow: gitleaks not installed, scan is skipped silently", func(t *testing.T) {
		k := New(t)
		k.Setenv("PATH", t.TempDir())
		r := k.Hook("guard-commit", `{"tool_input":{"command":"git commit -m \"feat: add foo\""}}`)
		r.Want(t, 0)
		r.Empty(t)
	})

	t.Run("gitleaks is invoked against payload .cwd, not the hook's own cwd", func(t *testing.T) {
		k := New(t)
		stubs := t.TempDir()
		argsFile := filepath.Join(t.TempDir(), "gitleaks.args")
		Stub(t, filepath.Join(stubs, "gitleaks"), fmt.Sprintf("echo \"$@\" > %q\nexit 0\n", argsFile))
		k.PrependPath(stubs)
		fixture := filepath.Join(Physical(t, t.TempDir()), "fixture-repo")
		Mkdir(t, fixture)
		k.Hook("guard-commit", guardCommitPayload(`git commit -m "feat: add foo"`, fixture)).Want(t, 0)
		if args := Read(t, argsFile); !strings.Contains(args, fixture) {
			t.Errorf("gitleaks args %q lack %q", args, fixture)
		}
	})
}
