#!/usr/bin/env bash
# PreToolUse hook for Bash. Inspects git commit commands for AI signatures
# and, per rules/adhd-output.md rule 8, an unchunked wall of text in the body.
HOOK_NAME="guard-commit.sh"
# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"

read_payload
require_jq

cmd="$(extract_command)"
[[ "$cmd" =~ git[[:space:]]+([^[:space:]]+[[:space:]]+)*commit ]] || exit 0

# AI signatures (Co-Authored-By, Generated by) may appear on any line of a
# multi-line message. Search $cmd directly -- line-by-line grep finds the
# trailer since it appears on its own line. Avoids -z (GNU-only, not macOS).
if printf '%s' "$cmd" | grep -qiE 'Co-Authored-By:[[:space:]]*Claude|Generated[[:space:]]+(by|with)[[:space:]]+Claude|🤖[[:space:]]*Generated'; then
  block "AI signature in commit message" "ai-commit-sig"
fi

# gitleaks exit codes: 0 = clean, 1 = leak found (--exit-code default),
# anything else is an operational error (bad flag, missing repo, version
# drift) and must fail open, not be conflated with a real finding. Runs
# before the subject-parsing early-exit below - unlike the AI-tell check,
# secret scanning must not depend on whether -m used a quoted message.
if command -v gitleaks >/dev/null 2>&1; then
  _cwd="$(printf '%s' "$payload" | jq -r '.cwd // empty' 2>/dev/null || true)"
  _gl_status=0
  gitleaks git --staged --no-banner --redact --log-level error "${_cwd:-.}" >/dev/null 2>&1 || _gl_status=$?
  if [[ "$_gl_status" -eq 1 ]]; then
    block "gitleaks flagged a secret in the staged diff" "staged-secret"
  elif [[ "$_gl_status" -ne 0 ]]; then
    warn "gitleaks exited $_gl_status (not a leak signal); skipping scan"
  fi
fi

# Wall-of-text check on the message body (rules/adhd-output.md rule 8). This
# repo's commit convention passes multi-line messages via a heredoc
# (`-m "$(cat <<'EOF' ... EOF)"`, per CLAUDE.md's git-commit example) -- pull
# the body between the heredoc opener and its closing EOF line. A plain
# single-line `-m "..."` has no heredoc and is skipped here; it's short
# enough that a miss is harmless.
heredoc_body="$(printf '%s\n' "$cmd" | sed -n "/<<-\\{0,1\\}['\"]\\{0,1\\}EOF['\"]\\{0,1\\}/,/^EOF\$/p" | sed '1d;$d' || true)"
if [[ -n "$heredoc_body" ]]; then
  run="$(longest_prose_run "$heredoc_body")"
  if ((run > 4)); then
    block "commit message has an unchunked wall of text (${run} consecutive prose lines). rules/adhd-output.md rule 8: short paragraphs, no dense blocks." "commit-wall-of-text"
  fi
fi

# Extract subject (first line of -m value) for AI-tell phrase check.
# Single-line grep is sufficient; we only need the subject, not the body.
msg_dq="$(printf '%s' "$cmd" | grep -oE '(-m|--message=?)[[:space:]]*"[^"]*"' | sed -E 's/.*"([^"]*)"/\1/' || true)"
msg_sq="$(printf '%s' "$cmd" | grep -oE "(-m|--message=?)[[:space:]]*'[^']*'" | sed -E "s/.*'([^']*)'/\1/" || true)"
subject="$(printf '%s' "${msg_dq}${msg_sq}" | head -1)"

[[ -z "$subject" ]] && exit 0

if echo "$subject" | grep -qiE '^(feat|fix|chore|refactor|docs|test|perf|build|ci|style)?:?[[:space:]]*(certainly|here is|i have|let me|in this commit|this commit)'; then
  block "AI-tell phrasing in commit subject" "ai-commit-tell"
fi

exit 0
