#!/bin/sh

brew cask install anvil
brew cask install battery-guardian
brew cask install caffeine
brew cask install chromecast
brew cask install coconutbattery
brew cask install cyberduck
brew cask install diffmerge
brew cask install dropbox
brew cask install firefox
brew cask install font-fontawesome
brew cask install font-sauce-code-powerline
brew cask install font-source-code-pro-for-powerline
brew cask install gfxcardstatus
brew cask install google-chrome
brew cask install google-drive
brew cask install iterm2
brew cask install macvim
brew cask install onyx
brew cask install screenhero
brew cask install sketch
brew cask install slack
brew cask install smcfancontrol
brew cask install spotify
brew cask install transmission
brew cask install tunnelbear
brew cask install vagrant
brew cask install virtualbox
brew cask install launchrocket
brew cask install vlc
